(function(){
  const K=window.KW,E=K.esc,ar=()=>K.getLang()==='ar',pc=v=>Math.max(0,Math.min(100,+v||0));
  const none=()=>`<div class="card"><p class="muted">${ar()?'مفيش نتائج.':'No results.'}</p></div>`;
  const pathCards=(l,full)=>l.map(p=>`<article class="card path-card card-hover"><div class="path-top"><div><div class="path-icon">${E(p.icon)}</div></div><span class="tag">${E(p.level)}</span></div><div><h3>${E(p.title)}</h3><p>${E(p.desc)}</p></div><div class="path-meta">${(p.topics||[]).slice(0,full?99:3).map(t=>`<span class="tag">${E(t)}</span>`).join('')}</div><div><div class="path-footer"><span class="small muted">${ar()?'تقدمك':'Your progress'} ${pc(p.progress)}%</span><a class="btn btn-soft small" href="path.html?id=${encodeURIComponent(p.id)}">${ar()?'فتح المسار':'Open path'}</a></div><div class="progress"><span style="width:${pc(p.progress)}%"></span></div></div></article>`).join('')||none();
  const articleCards=l=>l.map(a=>`<article class="card article-card card-hover"><div class="article-cover mono">${E(a.icon)}</div><div class="article-body"><div class="article-meta"><span>${E(a.cat)}</span><span>${E(a.time)}</span></div><h3>${E(a.title)}</h3><p>${E(a.desc)}</p><a class="btn btn-ghost small" href="article.html?id=${encodeURIComponent(a.id)}">${ar()?'اقرأ المقال':'Read article'}</a></div></article>`).join('')||none();
  const quizCards=l=>l.map(q=>`<article class="card quiz-card card-hover"><div class="quiz-icon mono">${E(q.icon)}</div><div><span class="tag accent">${E(q.difficulty)}</span><h3>${E(q.title)}</h3><p>${+q.questions} ${ar()?'أسئلة':'questions'} · ${+q.xp} XP</p></div><div class="quiz-actions"><span class="small muted">${E(q.cat)}</span><a class="btn btn-primary small" href="quiz.html?id=${encodeURIComponent(q.id)}">${ar()?'ابدأ':'Start'}</a></div></article>`).join('')||none();
  const inline=s=>E(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
  const one=b=>b.type==='h2'?`<h2>${inline(b.text)}</h2>`:b.type==='p'?`<p>${inline(b.text)}</p>`:(b.type==='ul'||b.type==='ol')?`<${b.type}>${(b.items||[]).map(x=>`<li>${inline(x)}</li>`).join('')}</${b.type}>`:b.type==='code'?`<pre class="code-block" dir="ltr"><code>${E(b.text)}</code></pre>`:b.type==='tip'?`<aside class="tip">💡 ${inline(b.text)}</aside>`:'';
  const norm=b=>{if(Array.isArray(b)){const t=String(b[0]||'');return t==='ul'||t==='ol'?{type:t,items:b[1]||[]}:t==='code'?{type:'code',lang:b[1],text:b[2]}:{type:t,text:b[1]}}return b&&typeof b==='object'?b:b==null?null:{type:'p',text:String(b)}};
  const blocks=l=>{if(typeof l==='string')l=l.split(/\n{2,}/).filter(x=>x.trim()).map(x=>({type:'p',text:x.trim()}));return (Array.isArray(l)?l:[]).map(norm).filter(Boolean).map(one).join('')};
  const sources=l=>{
    if(!(l||[]).length)return '';
    return `<section class="article-sources" aria-labelledby="sourcesTitle"><h2 id="sourcesTitle">${ar()?'المصادر والمراجع':'Sources & references'}</h2><p class="muted small">${ar()?'روابط للتوسع والتحقق من الأفكار المذكورة في المقال.':'Useful references for further reading and verification.'}</p><ul class="source-links">${l.map(s=>`<li><a href="${E(s.url)}" target="_blank" rel="noopener noreferrer">${E(s.title)}</a><span class="source-domain">${E(new URL(s.url).hostname.replace(/^www\./,''))}</span></li>`).join('')}</ul></section>`;
  };
  window.KW_RENDER={pathCards,articleCards,quizCards,blocks,sources};
})();
