/* كتالوج المصادر المجانية + الرودماب لكل مسار.
   مصدر: [العنوان, الرابط, اللغة (ar|en), النوع, وصف قصير]
   مرحلة: [العنوان, الوصف, المدة, مشروع/تحقق, [مفاتيح المصادر]]  */
(function(){
const R={
/* مصادر عربية عامة */
aia:['Awesome in Arabic','https://github.com/abdumostafa/awesome-in-arabic','ar','list','قايمة مجمّعة لقنوات وكورسات ومحتوى تقني بالعربي'],
hsoub:['أكاديمية حسوب','https://academy.hsoub.com','ar','docs','شروحات ومقالات تقنية مجانية بالعربي'],
pa:['Programming Advices','https://www.youtube.com/@ProgrammingAdvices','ar','video','أساسيات البرمجة وحل المشكلات بالعربي'],
elz:['Elzero Web School','https://www.youtube.com/@ElzeroWebSchool','ar','video','كورسات كاملة: HTML وCSS وJS وPython وSQL'],
edraak:['إدراك','https://www.edraak.org','ar','course','كورسات عربية مجانية، دوّر فيها على البرمجة والبيانات'],
mslar:['Microsoft Learn بالعربي','https://learn.microsoft.com/ar-sa/training/','ar','course','مسارات مجانية، وحدات كتير منها مترجمة'],
khanar:['خان أكاديمي بالعربي','https://ar.khanacademy.org','ar','course','دروس رياضيات مجانية (المحتوى العربي جزئي)'],
fpb:['Free Programming Books','https://github.com/EbookFoundation/free-programming-books','en','list','أكبر قايمة كتب وكورسات مجانية، وفيها أقسام بالعربي'],
/* ويب */
fcc:['freeCodeCamp','https://www.freecodecamp.org/learn','en','course','منهج كامل بتمارين ومشاريع'],
mdn:['MDN: Learn Web Development','https://developer.mozilla.org/en-US/docs/Learn_web_development','en','docs','المرجع الأول لتعلم الويب'],
webdev:['web.dev Learn','https://web.dev/learn?hl=ar','ar','course','HTML وCSS وJS وإمكانية الوصول من Google (ترجمة عربية آلية)'],
jsar:['javascript.info بالعربي','https://ar.javascript.info','ar','docs','JavaScript الحديثة بالتفصيل مع تمارين'],
jsen:['The Modern JavaScript Tutorial','https://javascript.info','en','docs','النسخة الأصلية والأحدث'],
odin:['The Odin Project','https://www.theodinproject.com','en','course','مسار Full Stack مجاني بمشاريع حقيقية'],
fso:['Full Stack Open','https://fullstackopen.com','en','course','كورس جامعة هلسنكي: React وNode وTesting'],
flex:['Flexbox Froggy','https://flexboxfroggy.com','en','practice','تعلم Flexbox بلعبة'],
grid:['CSS Grid Garden','https://cssgridgarden.com','en','practice','تعلم Grid بلعبة'],
fem:['Frontend Mentor','https://www.frontendmentor.io','en','practice','تحديات تصميم جاهزة لبناء Portfolio'],
react:['React: Learn','https://react.dev/learn','en','docs','الدليل الرسمي لـ React'],
nodel:['Node.js: Learn','https://nodejs.org/en/learn','en','docs','أساسيات Node.js من الموقع الرسمي'],
rest:['RESTful API Tutorial','https://restfulapi.net','en','docs','مبادئ تصميم REST APIs'],
mdnhttp:['MDN: HTTP','https://developer.mozilla.org/en-US/docs/Web/HTTP','en','docs','الـheaders والـstatus codes وكل حاجة عن HTTP'],
ghp:['GitHub Pages Docs','https://docs.github.com/en/pages','en','docs','انشر موقعك مجانًا'],
/* علوم الحاسب */
cs50x:['CS50x','https://cs50.harvard.edu/x','en','course','أشهر مدخل لعلوم الحاسب، مجاني بالكامل'],
cs50p:['CS50 Python','https://cs50.harvard.edu/python','en','course','Python من الصفر مع تصحيح تلقائي'],
tycs:['Teach Yourself CS','https://teachyourselfcs.com','en','list','خريطة كتب وكورسات لكل مواد علوم الحاسب'],
n2t:['Nand2Tetris','https://www.nand2tetris.org','en','course','ابنِ كمبيوتر كامل من البوابات المنطقية'],
ostep:['Operating Systems: Three Easy Pieces','https://pages.cs.wisc.edu/~remzi/OSTEP/','en','book','أشهر كتاب مجاني لأنظمة التشغيل'],
mit6006:['MIT 6.006: Introduction to Algorithms','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/','en','course','محاضرات خوارزميات كاملة'],
algs4:['Algorithms, 4th Edition','https://algs4.cs.princeton.edu/home/','en','book','موقع كتاب Sedgewick مع شروحات وكود'],
visualgo:['VisuAlgo','https://visualgo.net','en','tool','شوف الخوارزميات وهي بتتنفذ'],
neetcode:['NeetCode','https://neetcode.io','en','practice','أسئلة LeetCode مرتبة حسب الفكرة'],
ms:['The Missing Semester (MIT)','https://missing.csail.mit.edu','en','course','الأدوات اللي الجامعة مش بتعلمهالك: shell وGit وdebugging'],
learncpp:['LearnCpp','https://www.learncpp.com','en','docs','أفضل شرح مجاني لـ C++'],
py4e:['Python for Everybody','https://www.py4e.com','en','course','Python للمبتدئين بمحاضرات وكتاب مجاني'],
/* ذكاء اصطناعي */
mlcc:['Machine Learning Crash Course','https://developers.google.com/machine-learning/crash-course?hl=ar','ar','course','دورة Google المكثفة في تعلم الآلة (ترجمة عربية)'],
fastai:['fast.ai: Practical Deep Learning','https://course.fast.ai','en','course','ابنِ نماذج حقيقية من أول درس'],
sklearn:['scikit-learn Tutorials','https://scikit-learn.org/stable/tutorial/index.html','en','docs','مكتبة ML الأساسية بأمثلة'],
hfl:['Hugging Face Learn','https://huggingface.co/learn','en','course','كورسات NLP وLLMs'],
karp:['Neural Networks: Zero to Hero','https://karpathy.ai/zero-to-hero.html','en','video','ابنِ شبكة عصبية من الصفر مع Andrej Karpathy'],
mml:['Mathematics for Machine Learning','https://mml-book.github.io','en','book','الرياضيات اللازمة لـ ML'],
b3:['3Blue1Brown: Linear Algebra','https://www.3blue1brown.com/topics/linear-algebra','en','video','أفضل تصور بصري للجبر الخطي'],
mit1806:['MIT 18.06 Linear Algebra','https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/','en','course','محاضرات Gilbert Strang الشهيرة'],
cs50ai:['CS50 AI','https://cs50.harvard.edu/ai','en','course','مبادئ الـAI عمليًا (Search وML وNLP)'],
kaggle:['Kaggle Learn','https://www.kaggle.com/learn','en','course','كورسات قصيرة: Python وPandas وML وSQL'],
/* علم البيانات */
pandas:['10 minutes to pandas','https://pandas.pydata.org/docs/user_guide/10min.html','en','docs','ابدأ بـ pandas في جلسة واحدة'],
numpy:['NumPy Quickstart','https://numpy.org/doc/stable/user/quickstart.html','en','docs','أساسيات المصفوفات'],
jup:['Try Jupyter','https://jupyter.org/try','en','tool','شغّل Notebook بدون تثبيت'],
sqlbolt:['SQLBolt','https://sqlbolt.com','en','practice','دروس SQL تفاعلية قصيرة'],
sqlmyst:['SQL Murder Mystery','https://mystery.knightlab.com','en','practice','حل لغز جريمة باستخدام SQL'],
khanstat:['Khan Academy: Statistics','https://www.khanacademy.org/math/statistics-probability','en','course','إحصاء واحتمالات من الأساس'],
openintro:['OpenIntro Statistics','https://www.openintro.org/book/os/','en','book','كتاب إحصاء مجاني'],
seeing:['Seeing Theory','https://seeing-theory.brown.edu','en','tool','الإحصاء بالرسوم التفاعلية'],
statq:['StatQuest','https://statquest.org','en','video','شرح مبسط جدًا للإحصاء وML'],
d2v:['From Data to Viz','https://www.data-to-viz.com','en','docs','اختار الرسم المناسب لبياناتك'],
mpl:['Matplotlib Tutorials','https://matplotlib.org/stable/tutorials/index.html','en','docs','رسم البيانات بـ Python'],
tableau:['Tableau Public','https://public.tableau.com','en','tool','اعمل Dashboards وانشرها مجانًا'],
kagd:['Kaggle Datasets','https://www.kaggle.com/datasets','en','tool','آلاف الداتاسيتس لمشاريعك'],
/* أمن سيبراني */
netacad:['Cisco Networking Academy','https://www.netacad.com','en','course','كورسات مجانية في الشبكات والأمن (بعضها بالعربي)'],
cfl:['Cloudflare Learning Center','https://www.cloudflare.com/learning/','en','docs','شرح مبسط للشبكات والأمان'],
messer:['Professor Messer','https://www.professormesser.com','en','video','شرح Network+ وSecurity+ مجانًا'],
thm:['TryHackMe','https://tryhackme.com','en','practice','غرف تعلم عملية للمبتدئين (فيه مستوى مجاني)'],
psw:['PortSwigger Web Security Academy','https://portswigger.net/web-security','en','course','أفضل مصدر مجاني لثغرات الويب مع Labs'],
owasp10:['OWASP Top 10','https://owasp.org/www-project-top-ten/','en','docs','أخطر 10 مخاطر لتطبيقات الويب'],
juice:['OWASP Juice Shop','https://owasp.org/www-project-juice-shop/','en','practice','تطبيق ضعيف عمدًا للتدريب القانوني'],
otw:['OverTheWire Wargames','https://overthewire.org/wargames/','en','practice','ألعاب تعلّم Linux والأمن من الصفر'],
pico:['picoCTF','https://picoctf.org','en','practice','مسابقات CTF للمبتدئين'],
wshark:['Wireshark Docs','https://www.wireshark.org/docs/','en','docs','تحليل الحزم عمليًا'],
lj:['Linux Journey','https://linuxjourney.com','en','course','Linux من الصفر بشكل مرتب'],
/* هندسة برمجيات */
gitbook:['Pro Git','https://git-scm.com/book/en/v2','en','book','الكتاب الرسمي لـ Git'],
lgb:['Learn Git Branching','https://learngitbranching.js.org','en','practice','تعلم الـbranching بتمارين بصرية'],
ghs:['GitHub Skills','https://skills.github.com','en','course','كورسات تفاعلية داخل GitHub'],
rg:['Refactoring Guru: Design Patterns','https://refactoring.guru/design-patterns','en','docs','شرح الـpatterns بأمثلة ورسومات'],
fowler:['Martin Fowler','https://martinfowler.com','en','docs','مقالات في التصميم والـRefactoring والـTesting'],
gep:['Google Engineering Practices','https://google.github.io/eng-practices/','en','docs','إزاي Google بتعمل Code Review'],
sweg:['Software Engineering at Google','https://abseil.io/resources/swe-book','en','book','كتاب مجاني عن ممارسات الهندسة'],
f12:['The Twelve-Factor App','https://12factor.net','en','docs','مبادئ بناء تطبيقات جاهزة للنشر'],
sdp:['System Design Primer','https://github.com/donnemartin/system-design-primer','en','list','مدخل لتصميم الأنظمة الكبيرة'],
jest:['Jest: Getting Started','https://jestjs.io/docs/getting-started','en','docs','كتابة أول Tests لـ JavaScript'],
/* موبايل */
flutter:['Flutter Docs','https://docs.flutter.dev','en','docs','التوثيق الرسمي وبداية التعلم'],
cookbook:['Flutter Cookbook','https://docs.flutter.dev/cookbook','en','docs','وصفات جاهزة لمهام شائعة'],
dart:['Dart Language','https://dart.dev/language','en','docs','تعلم لغة Dart'],
statemg:['Flutter: State Management','https://docs.flutter.dev/data-and-backend/state-mgmt/intro','en','docs','إدارة الحالة خطوة بخطوة'],
riverpod:['Riverpod','https://riverpod.dev','en','docs','إدارة حالة حديثة لـ Flutter'],
m3:['Material Design 3','https://m3.material.io','en','docs','مبادئ وعناصر تصميم الموبايل'],
firebase:['Firebase for Flutter','https://firebase.google.com/docs/flutter/setup','en','docs','Auth وقواعد بيانات جاهزة'],
compose:['Android Basics with Compose','https://developer.android.com/courses/android-basics-compose/course','en','course','كورس Google لتطبيقات Android'],
/* سحابة */
tlcl:['The Linux Command Line','https://linuxcommand.org/tlcl.php','en','book','كتاب مجاني عن الطرفية'],
docker:['Docker: Get Started','https://docs.docker.com/get-started/','en','docs','أول Container لك'],
k8s:['Kubernetes Basics','https://kubernetes.io/docs/tutorials/kubernetes-basics/','en','course','أساسيات Kubernetes بتمارين'],
awssb:['AWS Skill Builder','https://skillbuilder.aws','en','course','كورسات AWS الرقمية (فيه محتوى مجاني)'],
az900:['Azure Fundamentals (AZ-900)','https://learn.microsoft.com/en-us/training/courses/az-900t00','en','course','أساسيات السحابة من Microsoft'],
tf:['Terraform Tutorials','https://developer.hashicorp.com/terraform/tutorials','en','course','البنية كـ Code'],
gha:['GitHub Actions Docs','https://docs.github.com/en/actions','en','docs','أتمتة الاختبار والنشر (CI/CD)'],
twn:['TechWorld with Nana','https://www.youtube.com/@TechWorldwithNana','en','video','DevOps وDocker وKubernetes بشرح مبسط'],
/* شبكات */
pn:['Practical Networking','https://www.practicalnetworking.net','en','docs','شرح مبسط للشبكات والـsubnetting'],
hpbn:['High Performance Browser Networking','https://hpbn.co','en','book','كتاب مجاني عن TCP وTLS وHTTP'],
beej:["Beej's Guide to Network Programming",'https://beej.us/guide/bgnet/','en','book','برمجة Sockets عمليًا'],
kurose:['Computer Networking: A Top-Down Approach','https://gaia.cs.umass.edu/kurose_ross/','en','course','محاضرات وفيديوهات مرافقة للكتاب'],
howdns:['How DNS Works','https://howdns.works','en','docs','شرح DNS بقصة مصورة'],
hnasr:['Hussein Nasser','https://www.youtube.com/@hnasr','en','video','شرح عميق للشبكات والـbackend'],
/* UX */
lawsux:['Laws of UX','https://lawsofux.com','en','docs','قواعد نفسية تحكم تصميم الواجهات'],
nng:['Nielsen Norman Group','https://www.nngroup.com/articles/','en','docs','أبحاث ومقالات UX موثوقة'],
heur:['10 Usability Heuristics','https://www.nngroup.com/articles/ten-usability-heuristics/','en','docs','أهم 10 مبادئ لتقييم الواجهات'],
figma:['Figma: Learn Design','https://www.figma.com/resources/learn-design/','en','course','مبادئ التصميم وأساسيات Figma'],
penpot:['Penpot','https://penpot.app','en','tool','أداة تصميم مفتوحة المصدر ومجانية'],
gfk:['Google Fonts Knowledge','https://fonts.google.com/knowledge','en','docs','الخطوط والـTypography من الأساس'],
a11yp:['The A11Y Project','https://www.a11yproject.com','en','docs','إمكانية الوصول عمليًا'],
contrast:['WebAIM Contrast Checker','https://webaim.org/resources/contrastchecker/','en','tool','اختبر تباين الألوان'],
atomic:['Atomic Design','https://atomicdesign.bradfrost.com','en','book','كتاب مجاني لبناء Design Systems'],
/* roadmap.sh */
rsfe:['roadmap.sh: Frontend','https://roadmap.sh/frontend','en','roadmap','خريطة مجتمعية كاملة للـFrontend'],
rsbe:['roadmap.sh: Backend','https://roadmap.sh/backend','en','roadmap','خريطة مجتمعية كاملة للـBackend'],
rscs:['roadmap.sh: Computer Science','https://roadmap.sh/computer-science','en','roadmap','خريطة علوم الحاسب'],
rsai:['roadmap.sh: AI & Data Scientist','https://roadmap.sh/ai-data-scientist','en','roadmap','خريطة الذكاء الاصطناعي وعلم البيانات'],
rsds:['roadmap.sh: Data Analyst','https://roadmap.sh/data-analyst','en','roadmap','خريطة محلل البيانات'],
rscy:['roadmap.sh: Cyber Security','https://roadmap.sh/cyber-security','en','roadmap','خريطة الأمن السيبراني'],
rssw:['roadmap.sh: Software Design & Architecture','https://roadmap.sh/software-design-architecture','en','roadmap','خريطة التصميم والمعمارية'],
rsfl:['roadmap.sh: Flutter','https://roadmap.sh/flutter','en','roadmap','خريطة Flutter'],
rsdo:['roadmap.sh: DevOps','https://roadmap.sh/devops','en','roadmap','خريطة DevOps'],
rsux:['roadmap.sh: UX Design','https://roadmap.sh/ux-design','en','roadmap','خريطة UX']
};
const S=(t,d,w,p,r)=>({t,d,w,p,r});
const M={
web:{extra:['rsfe','rsbe'],stages:[
S('HTML: أساس أي صفحة','الهيكل الدلالي والنماذج وإمكانية الوصول.','أسبوعين','صفحة شخصية بهيكل دلالي صحيح',['webdev','elz','mdn']),
S('CSS والتصميم المتجاوب','التنسيق وFlexbox وGrid وتصميم يناسب كل الشاشات.','3 أسابيع','انسخ تصميم صفحة حقيقية من Frontend Mentor',['webdev','flex','grid','fem','elz']),
S('JavaScript','اللغة والـDOM والأحداث وasync وfetch.','6 أسابيع','تطبيق مهام أو لعبة صغيرة بدون مكتبات',['jsar','jsen','mdn','fcc']),
S('Git والنشر','التحكم في النسخ ونشر موقعك مجانًا.','أسبوع','انشر مشروعك على GitHub Pages',['gitbook','lgb','ghp']),
S('React وأدوات الـFrontend','المكونات والحالة وبناء واجهات كبيرة.','5 أسابيع','حوّل تطبيق المهام لـ React',['react','odin','fso']),
S('Backend وAPIs','Node وREST وقواعد البيانات والـAuth.','6 أسابيع','API بسيط لتطبيق المهام مع تسجيل دخول',['nodel','rest','mdnhttp','fso','sqlbolt'])]},
cs:{extra:['rscs','tycs'],stages:[
S('البرمجة وحل المشكلات','لغة واحدة (Python أو C++) وأساسيات التفكير البرمجي.','6 أسابيع','حل 10 مسائل من الصفر',['cs50x','cs50p','learncpp','pa']),
S('هياكل البيانات','Arrays وLinked Lists وStacks وQueues وTrees وHash Tables.','6 أسابيع','ابنِ Stack وQueue بنفسك',['visualgo','algs4','pa']),
S('الخوارزميات والتعقيد','Big O والبحث والترتيب والـRecursion والـDP.','8 أسابيع','حل 50 مسألة مرتبة بالفكرة',['mit6006','neetcode','algs4']),
S('كيف يعمل الحاسب','من البوابات المنطقية للمعالج والـassembly.','6 أسابيع','أنهِ أول 3 مشاريع في Nand2Tetris',['n2t','tycs']),
S('أنظمة التشغيل','العمليات والذاكرة والـthreads وملفات النظام.','6 أسابيع','اكتب Shell مبسّط',['ostep','ms']),
S('الشبكات وقواعد البيانات','TCP/IP وHTTP وSQL وتصميم الجداول.','6 أسابيع','تطبيق صغير بقاعدة بيانات',['hpbn','sqlbolt','cs50x'])]},
ai:{extra:['rsai','mslar'],stages:[
S('Python للبيانات','Python وNumPy وpandas وJupyter.','4 أسابيع','حلّل ملف CSV واطلع 5 استنتاجات',['py4e','kaggle','numpy','jup']),
S('الرياضيات الأساسية','جبر خطي وتفاضل واحتمالات وإحصاء.','6 أسابيع','ابنِ Linear Regression بالـNumPy بدون مكتبات ML',['b3','mit1806','khanstat','mml','khanar']),
S('Machine Learning الكلاسيكي','Regression وClassification وتقييم النماذج.','8 أسابيع','نموذج يتنبأ بأسعار أو يصنّف بيانات',['mlcc','sklearn','kaggle','statq']),
S('Deep Learning','الشبكات العصبية وCNN وTransformers.','8 أسابيع','مصنّف صور بنسبة دقة موثقة',['fastai','karp','cs50ai']),
S('NLP والنماذج اللغوية','معالجة النصوص واستخدام LLMs.','4 أسابيع','أداة تلخيص أو بحث دلالي',['hfl']),
S('مشاريع ونشر','Portfolio ونموذج منشور يجربه الناس.','4 أسابيع','ادخل مسابقة على Kaggle',['kagd','kaggle','hfl'])]},
ds:{extra:['rsds','edraak'],stages:[
S('Python وSQL','قراءة البيانات وتنظيفها واستعلامها.','5 أسابيع','20 استعلام SQL على بيانات حقيقية',['kaggle','sqlbolt','sqlmyst','py4e']),
S('pandas وتنظيف البيانات','التعامل مع الجداول والقيم المفقودة والتجميع.','3 أسابيع','نظّف داتاسيت فيه أخطاء وقيم ناقصة',['pandas','kaggle','numpy']),
S('الإحصاء والاحتمالات','الوصف والتوزيعات والاستدلال واختبار الفرضيات.','6 أسابيع','حلّل تجربة A/B وفسّر النتيجة',['khanstat','openintro','seeing','statq','khanar']),
S('تصور البيانات','اختيار الرسم المناسب وسرد القصة بالبيانات.','3 أسابيع','Dashboard واحد على Tableau Public',['d2v','mpl','tableau']),
S('ML للتنبؤ','نماذج تنبؤية وتقييمها.','6 أسابيع','نموذج تنبؤ مع شرح لنقاط ضعفه',['mlcc','sklearn','kaggle']),
S('مشروع تحليل كامل','سؤال حقيقي ← بيانات ← تحليل ← عرض.','4 أسابيع','تقرير منشور على GitHub أو Kaggle',['kagd','jup'])]},
cyber:{extra:['rscy','netacad'],stages:[
S('أساسيات الشبكات','IP وDNS وHTTP والـports.','4 أسابيع','اشرح رحلة طلب HTTP بالتفصيل',['netacad','messer','cfl','pn']),
S('Linux والطرفية','التنقل والصلاحيات والعمليات.','3 أسابيع','أنهِ 10 مستويات من Bandit',['lj','otw','ms']),
S('أساسيات الأمن','CIA والتشفير والـAuth والتهديدات الشائعة.','4 أسابيع','ألخّص 5 هجمات شائعة وطرق الدفاع',['messer','cfl','thm']),
S('أمان الويب','OWASP Top 10 وSQLi وXSS وأخطاء الـAuth.','6 أسابيع','حل 10 Labs في PortSwigger',['owasp10','psw','juice']),
S('التدريب العملي (بشكل قانوني)','Labs وCTF ومسابقات مسموحة.','مستمر','شارك في picoCTF',['thm','otw','pico','wshark']),
S('الأمن الدفاعي','المراقبة واللوجات والاستجابة للحوادث.','6 أسابيع','حلّل لوج هجوم وحدد مؤشراته',['thm','messer','cfl'])]},
software:{extra:['rssw','sdp'],stages:[
S('Git وGitHub','Branches وPull Requests وحل التعارضات.','أسبوعين','اعمل Pull Request في مشروع مفتوح المصدر',['gitbook','lgb','ghs']),
S('الكود النظيف','التسمية والدوال الصغيرة وإزالة التكرار.','3 أسابيع','عمل Refactoring لمشروع قديم لك',['fowler','gep']),
S('الاختبارات','Unit وIntegration وTDD.','3 أسابيع','غطّي مشروعك بـ 20 اختبار',['jest','fowler']),
S('OOP وDesign Patterns','مبادئ SOLID وأهم الأنماط.','5 أسابيع','طبّق 3 patterns في مشروع فعلي',['rg','fowler']),
S('العمل الجماعي والعمليات','Code Review وAgile وCI/CD.','3 أسابيع','ضيف CI يشغّل الاختبارات تلقائيًا',['gep','sweg','gha']),
S('تصميم الأنظمة','Architecture وقابلية التوسع.','6 أسابيع','ارسم تصميم تطبيق لمليون مستخدم',['sdp','f12','sweg'])]},
mobile:{extra:['rsfl','compose'],stages:[
S('أساسيات Dart','المتغيرات والدوال وOOP.','3 أسابيع','برنامج Console صغير بـ Dart',['dart','flutter']),
S('أساسيات Flutter','Widgets وLayouts والتنقل.','4 أسابيع','تطبيق من 3 شاشات',['flutter','cookbook']),
S('تصميم الواجهات','Material 3 والتجاوب مع الأحجام.','أسبوعين','طبّق تصميم Figma حرفيًا',['m3','cookbook']),
S('إدارة الحالة','setState وProvider وRiverpod.','3 أسابيع','تطبيق مهام بحالة مشتركة',['statemg','riverpod']),
S('الشبكات وBackend','استدعاء API وتخزين البيانات وFirebase.','4 أسابيع','تطبيق بتسجيل دخول وبيانات سحابية',['cookbook','firebase','rest']),
S('النشر','بناء نسخة Release ونشرها على المتاجر.','أسبوعين','انشر نسخة تجريبية لأصحابك',['flutter'])]},
cloud:{extra:['rsdo','mslar'],stages:[
S('Linux والشبكات','الأساس لأي عمل على السيرفرات.','4 أسابيع','ثبّت سيرفر وادخل عليه بـ SSH',['lj','tlcl','pn']),
S('Git والأتمتة','Shell scripting والتحكم في النسخ.','أسبوعين','سكربت نسخ احتياطي تلقائي',['ms','gitbook']),
S('Docker','Containers وImages وCompose.','3 أسابيع','ضع تطبيقًا كاملًا في Container',['docker','twn']),
S('أساسيات السحابة','Compute وStorage وNetworking وIAM.','4 أسابيع','انشر موقعًا static على السحابة',['awssb','az900','mslar']),
S('CI/CD وInfrastructure as Code','Pipelines وTerraform.','4 أسابيع','Pipeline ينشر تلقائيًا عند كل push',['gha','tf','twn']),
S('Kubernetes والمراقبة','Orchestration وMonitoring.','5 أسابيع','شغّل تطبيقًا على Kubernetes محليًا',['k8s','twn'])]},
networks:{extra:['netacad','fpb'],stages:[
S('أساسيات الشبكات','نماذج OSI وTCP/IP والعناوين والـports.','3 أسابيع','ارسم رحلة طلب ويب من المتصفح للسيرفر',['netacad','pn','messer','kurose']),
S('الـIP والـSubnetting','IPv4/IPv6 وتقسيم الشبكات.','3 أسابيع','قسّم شبكة لأربع Subnets يدويًا',['pn','messer','netacad']),
S('Routing وSwitching','VLANs وRouting وأهم البروتوكولات.','5 أسابيع','ابنِ شبكة صغيرة في Packet Tracer',['netacad','messer']),
S('البروتوكولات العليا','DNS وHTTP وTLS.','3 أسابيع','تتبّع طلب HTTPS بأدوات المتصفح',['howdns','mdnhttp','cfl','hpbn']),
S('تحليل الحزم والتشخيص','Wireshark وping وtraceroute.','أسبوعين','التقط حزم DNS وHTTP وحللها',['wshark','beej','hnasr']),
S('أمن الشبكات','Firewalls وVPN وIDS.','4 أسابيع','اضبط جدار حماية على جهاز تجريبي',['messer','cfl','thm'])]},
ux:{extra:['rsux','hsoub'],stages:[
S('أساسيات التصميم','التباين والمحاذاة والألوان والخطوط.','3 أسابيع','أعد تصميم صفحة سيئة',['figma','gfk','lawsux']),
S('أبحاث المستخدم','Interviews وPersonas وUser Flows.','3 أسابيع','قابل 5 مستخدمين واكتب النتائج',['nng','heur']),
S('التصميم في Figma','Wireframes وPrototypes.','3 أسابيع','Prototype تفاعلي لتطبيق كامل',['figma','penpot']),
S('إمكانية الوصول','الألوان والتباين وقارئات الشاشة.','أسبوعين','راجع موقعًا وسجّل 10 مشاكل وصول',['a11yp','contrast','webdev']),
S('Design Systems','مكوّنات وتوكنز متسقة.','3 أسابيع','ابنِ Design System صغير',['atomic','m3']),
S('Portfolio','3 Case Studies حقيقية.','4 أسابيع','انشر Portfolio على الإنترنت',['fem','nng'])]}
};
const HUBS=['aia','hsoub','pa','elz','edraak','fpb'];
window.KW_DATA.res=R;window.KW_DATA.roadmaps=M;window.KW_DATA.hubs=HUBS;
})();
